# SPDX-FileCopyrightText: 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""Immutable contracts for the kernel rewrite controller."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from kernelforge.knowledge.kernel_identity import KernelRecipeIdentity

TASK_SCHEMA_VERSION = 1
TASK_STATE_SCHEMA_VERSION = 1

TASK_FILENAME = "task.json"
DRIVER_FILENAME = "driver.py"
STATE_FILENAME = "state.json"

WORKLOAD_FILENAME = "workload.md"
SERVING_CONTEXT_FILENAME = "serving-context.md"
TRACE_EVIDENCE_FILENAME = "trace-evidence.md"

TASK_STATUS_READY = "ready"
TASK_STATUS_RUNNING = "running"
TASK_STATUS_SUCCEEDED = "succeeded"
TASK_STATUS_FAILED = "failed"
TASK_STATUS_SKIPPED = "skipped"
TASK_STATUSES = frozenset(
    {
        TASK_STATUS_READY,
        TASK_STATUS_RUNNING,
        TASK_STATUS_SUCCEEDED,
        TASK_STATUS_FAILED,
        TASK_STATUS_SKIPPED,
    }
)
TERMINAL_TASK_STATUSES = frozenset(
    {
        TASK_STATUS_SUCCEEDED,
        TASK_STATUS_FAILED,
        TASK_STATUS_SKIPPED,
    }
)


class HandoffContractError(ValueError):
    """The handoff directory cannot be consumed."""


class TaskContractError(ValueError):
    """One operator task is malformed or inconsistent."""


class TaskStateError(ValueError):
    """A persisted task state is malformed or an invalid transition."""


@dataclass(frozen=True)
class HandoffBundle:
    """The three Markdown documents supplied by Hyperloom."""

    root: Path
    workload: str
    serving_context: str
    trace_evidence: str


@dataclass(frozen=True)
class KernelRewriteTask:
    """One deterministic controller task generated by the analysis agent."""

    identity: KernelRecipeIdentity
    operator_id: str
    base_commit: str
    repo_root: Path
    kernel_path: str
    operator_name: str
    driver_path: str
    priority: int
    source_files: tuple[str, ...] = ()
    target_functions: tuple[str, ...] = ()
    shape_cases: tuple[dict[str, Any], ...] = ()
    reason: str = ""
    evidence: tuple[Any, ...] = ()
    schema_version: int = TASK_SCHEMA_VERSION


@dataclass(frozen=True)
class TaskParseResult:
    """A parsed task or the reason that task was skipped."""

    task: KernelRewriteTask | None = None
    reason: str = ""

    @property
    def ok(self) -> bool:
        return self.task is not None


@dataclass(frozen=True)
class TaskState:
    """Durable state for one operator task."""

    status: str
    reason: str = ""
    started_at: str = ""
    finished_at: str = ""
    workspace_dir: str = ""
    result_patch_dir: str = ""
    schema_version: int = field(default=TASK_STATE_SCHEMA_VERSION, init=False)

    def __post_init__(self) -> None:
        if self.status not in TASK_STATUSES:
            raise TaskStateError(f"unsupported task status: {self.status!r}")
        for name in ("reason", "started_at", "finished_at", "workspace_dir", "result_patch_dir"):
            if not isinstance(getattr(self, name), str):
                raise TaskStateError(f"TaskState.{name} must be a string")

    def to_dict(self) -> dict[str, Any]:
        """Return the canonical JSON representation."""
        return asdict(self)

    @classmethod
    def from_dict(cls, payload: Any) -> "TaskState":
        """Validate and deserialize a persisted task state."""
        if not isinstance(payload, dict):
            raise TaskStateError("task state must be a JSON object")
        expected = {
            "schema_version",
            "status",
            "reason",
            "started_at",
            "finished_at",
            "workspace_dir",
            "result_patch_dir",
        }
        unknown = set(payload) - expected
        if unknown:
            raise TaskStateError(f"task state has unknown fields: {', '.join(sorted(unknown))}")
        version = payload.get("schema_version")
        if isinstance(version, bool) or version != TASK_STATE_SCHEMA_VERSION:
            raise TaskStateError(f"unsupported task state schema {version!r}; expected {TASK_STATE_SCHEMA_VERSION}")
        status = payload.get("status")
        if not isinstance(status, str):
            raise TaskStateError("TaskState.status must be a string")
        values: dict[str, str] = {}
        for name in ("reason", "started_at", "finished_at", "workspace_dir", "result_patch_dir"):
            value = payload.get(name, "")
            if not isinstance(value, str):
                raise TaskStateError(f"TaskState.{name} must be a string")
            values[name] = value
        return cls(status=status, **values)


__all__ = [
    "DRIVER_FILENAME",
    "HandoffBundle",
    "HandoffContractError",
    "KernelRewriteTask",
    "SERVING_CONTEXT_FILENAME",
    "STATE_FILENAME",
    "TASK_FILENAME",
    "TASK_SCHEMA_VERSION",
    "TASK_STATE_SCHEMA_VERSION",
    "TASK_STATUSES",
    "TASK_STATUS_FAILED",
    "TASK_STATUS_READY",
    "TASK_STATUS_RUNNING",
    "TASK_STATUS_SKIPPED",
    "TASK_STATUS_SUCCEEDED",
    "TERMINAL_TASK_STATUSES",
    "TRACE_EVIDENCE_FILENAME",
    "TaskContractError",
    "TaskParseResult",
    "TaskState",
    "TaskStateError",
    "WORKLOAD_FILENAME",
]
